# Site
name: 'Блог Clixby'
description: 'Блог проекта Clixby'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'demowebsite'
email: 'poltavtcev@gmail.com'
mailchimp-list: 'https://mrlinks.us19.list-manage.com/subscribe?u=d70f5045034f1ae80c4d93f6c&id=5f3a7801d3'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    poltavcev:
      name:           Poltavcev
      site:           https://poltavcev.biz
      avatar:         assets/images/avatar1.jpg
      bio:            "Привет, меня зовут Николай, я владелец сервиса Clixby блог которого вы сейчас читаете. Надеюсь вам нравится блог и сервис."
      email:          poltavtcev@gmail.com
      twitter:        https://twitter.com/poltavtcev
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Localization
languages: ["ru", "en"]
exclude_from_localizations: ["javascript", "images", "css"]

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
